development:

  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cards_development
  pool: 5
  username: alexandra
  password: barvac

test:

  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cards_test
  pool: 5
  username: alexandra
  password: barvac

production:

  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cards_development
  pool: 5
  username: alexandra
  password: barvac
