development:

adapter: postgresql
host: localhost
encoding: unicode
database: cards_development
pool: 5

test:

adapter: postgresql
host: localhost
encoding: unicode
database: cards_development
pool: 5

production:

adapter: postgresql
host: localhost
encoding: unicode
database: cards_development
pool: 5
